### ISSUE TITLE
"unknown" in tracking

### ISSUE THREAD

**Issue by perjmolsen** [flashg1/TeslaSolarCharger#17]
Hi

First of all - thanks for your Tesla charger automation :)

It's working perfect for my new Tesla model 3 highland, and Tesla wall charger gen 3
, but I have an issue - that I do now know if its an error, or just by design. :)

If I look at the tracking details, from the automation - I get "unknown" sometimes... Is that an error? 

![unknown](https://github.com/flashg1/TeslaSolarCharger/assets/126662740/cbda6d9b-9108-469e-aba0-d7b36201100b)

My Automation is set up using Teslametry 

My automation is set up like this:
https://pastebin.com/mGaRCqju

My Tesla_solar_charger_automation.yaml looks like this:
https://pastebin.com/kgBrvysA

The only thing that I have changed is
1. Tesla location - because my location is not working, I have made a change so its charging when its "not_home"
2.  Car wake up is lowered to: 20
3. Wait grid power net update: 5 (I am using Simelezer +)
4 Skew_default: is set to -1

**Comment by flashg1** [comment]
Glad it is working for you.

At the moment, I'm not seeing any "unknown" in log, but will check again later.

Tesla location not working ... you need to set up your home location in HA first, ie. Settings > System > General > Edit location

**Comment by flashg1** [comment]
Just checked again.  I did not see any "Unknown events".  Closing case unless this is still an issue.
