### ISSUE TITLE
Trigger the automation when the charger was plugged in earlier, but charging is started through the tesla app

### ISSUE THREAD

**Issue by ddeconin-gh** [flashg1/TeslaSolarCharger#21]
If the tesla is plugged in, but charging is stopped at some time (through the app for example), the automation stops running.
If it is then started again through the Tesla app, this doesn't trigger a new automation execution.
This is because the sensor.charger itself doesn't change from off to on, but the attribute 'charging_state' changes instead.

**Comment by flashg1** [comment]
To make thing simple, I suggest to just control the charging via HA.

**Comment by flashg1** [comment]
Closing case unless this is still an issue.
