### ISSUE TITLE
Error: TypeError: '>' not supported ...... issue, what is wrong? 

### ISSUE THREAD

**Issue by rgroothuis** [flashg1/TeslaSolarCharger#23]
I'm installing the Blueprint and configuring it for the first time. Still learning and checking if everything is set correctly. But I got the following error message: 

Error: TypeError: '>' not supported between instances of 'str' and 'int'

See also included screenshot. And the script is not running anymore (I guess) because the Amps are not changing. 

<img width="1448" alt="Screenshot 2024-08-21 at 10 53 33" src="https://github.com/user-attachments/assets/70dd736c-6d45-4120-9c0c-bef97586b1ee">

And this is my Blueprint configuration so it can be checked if the configuration is done correctly. Segolene is the name of my Tesla Y. 

<img width="1168" alt="Screenshot 2024-08-21 at 10 56 50" src="https://github.com/user-attachments/assets/7e6f858c-f94d-496d-aff6-f787a491fd31">
<img width="1222" alt="Screenshot 2024-08-21 at 10 57 05" src="https://github.com/user-attachments/assets/ffd70fb5-fe5a-4562-9725-d5d3d5d3b091">
<img width="1240" alt="Screenshot 2024-08-21 at 10 57 11" src="https://github.com/user-attachments/assets/87b54b99-362e-4e23-baa1-36c0e1ea69fd">

**Comment by flashg1** [comment]
This response is bit late, but late is better than never!

Suggest to click on the "Changed variables" tab and look at the values under iteration 3.  There might be some clue as to which variable is causing this error.

**Comment by flashg1** [comment]
Suspect issue might be related to how you set up your inverter "Grid Power Net" sensor. Please check out this [FAQ](https://github.com/flashg1/TeslaSolarCharger/wiki/FAQ).

Closing case unless you have further comments.
